
---
- name: set locale
  shell: export LC_ALL="en_US.UTF-8" && export LANGUAGE="en_US.UTF-8" && locale >> /etc/environment
  sudo: yes

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600
  sudo: yes

- name: install required software
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - curl
    - gnupg
    - fail2ban
    - ufw
    - wget
    - rsync
    - git
    - zip
    - build-essential
    - vim
    - chkrootkit
    - psmisc

- name: ensure fail2ban is running
  sudo: yes
  action: service name=fail2ban state=restarted enabled=yes

- name: forbid SSH root login
  sudo: yes
  lineinfile: destfile=/etc/ssh/sshd_config regexp="^PermitRootLogin" line="PermitRootLogin no" state=present
  notify: restart ssh

- name: reset firewall
  sudo: yes
  action: shell ufw --force reset

- name: allow firewall authorized ports
  sudo: yes
  action: shell ufw allow {{ item }}
  with_items:
  - 22
  - 80

- name: enable firewall
  sudo: yes
  action: shell ufw --force enable
